name: Lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: yarn install
      - run: yarn fix:prettier
      - run: yarn fix:lint
