name: Lint

on:
  push:
    branches:
      - staging
    paths:
      - "packages/web/**"
      - "packages/api/**"
  pull_request:
    branches:
      - staging
    paths:
      - "packages/web/**"
      - "packages/api/**"
jobs:
  test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1

      - run: yarn install
      - run: cd packages/web && yarn lint
      - run: cd packages/api && yarn lint
        id: test
